ALTER TABLE cerner.address ADD CONSTRAINT contact_name_sensitive_check CHECK (contact_name is null);
ALTER TABLE cerner.diagnosis ADD CONSTRAINT diag_prsnl_name_sensitive_check CHECK (diag_prsnl_name is null);
ALTER TABLE cerner.encounter ADD CONSTRAINT name_first_key_sensitive_check CHECK (name_first_key is null);
ALTER TABLE cerner.encounter ADD CONSTRAINT name_first_sensitive_check CHECK (name_first is null);
ALTER TABLE cerner.encounter ADD CONSTRAINT name_first_synonym_id_sensitive_check CHECK (name_first_synonym_id is null);
ALTER TABLE cerner.encounter ADD CONSTRAINT name_full_formatted_sensitive_check CHECK (name_full_formatted is null);
ALTER TABLE cerner.encounter ADD CONSTRAINT name_last_key_sensitive_check CHECK (name_last_key is null);
ALTER TABLE cerner.encounter ADD CONSTRAINT name_last_sensitive_check CHECK (name_last is null);
ALTER TABLE cerner.encounter ADD CONSTRAINT name_phonetic_sensitive_check CHECK (name_phonetic is null);
ALTER TABLE cerner.person ADD CONSTRAINT mother_maiden_name_sensitive_check CHECK (mother_maiden_name is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_first_key_a_nls_sensitive_check CHECK (name_first_key_a_nls is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_first_key_nls_sensitive_check CHECK (name_first_key_nls is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_first_key_sensitive_check CHECK (name_first_key is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_first_phonetic_sensitive_check CHECK (name_first_phonetic is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_first_sensitive_check CHECK (name_first is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_first_synonym_id_sensitive_check CHECK (name_first_synonym_id is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_full_formatted_sensitive_check CHECK (name_full_formatted is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_last_key_a_nls_sensitive_check CHECK (name_last_key_a_nls is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_last_key_nls_sensitive_check CHECK (name_last_key_nls is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_last_key_sensitive_check CHECK (name_last_key is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_last_phonetic_sensitive_check CHECK (name_last_phonetic is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_last_sensitive_check CHECK (name_last is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_middle_key_a_nls_sensitive_check CHECK (name_middle_key_a_nls is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_middle_key_nls_sensitive_check CHECK (name_middle_key_nls is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_middle_key_sensitive_check CHECK (name_middle_key is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_middle_sensitive_check CHECK (name_middle is null);
ALTER TABLE cerner.person ADD CONSTRAINT name_phonetic_sensitive_check CHECK (name_phonetic is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT email_sensitive_check CHECK (email is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT name_first_key_a_nls_sensitive_check CHECK (name_first_key_a_nls is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT name_first_key_nls_sensitive_check CHECK (name_first_key_nls is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT name_first_key_sensitive_check CHECK (name_first_key is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT name_first_sensitive_check CHECK (name_first is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT name_full_formatted_sensitive_check CHECK (name_full_formatted is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT name_last_key_a_nls_sensitive_check CHECK (name_last_key_a_nls is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT name_last_key_nls_sensitive_check CHECK (name_last_key_nls is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT name_last_key_sensitive_check CHECK (name_last_key is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT name_last_sensitive_check CHECK (name_last is null);
ALTER TABLE cerner.prsnl ADD CONSTRAINT username_sensitive_check CHECK (username is null);
ALTER TABLE cerner.prsnl_group add CONSTRAINT prsnl_group_name_key_a_nls_sensitive_chec CHECK (prsnl_group_name_key_a_nls is null);
ALTER TABLE cerner.prsnl_group add CONSTRAINT prsnl_group_name_key_nls_sensitive_chec CHECK (prsnl_group_name_key_nls is null);
ALTER TABLE cerner.prsnl_group add CONSTRAINT prsnl_group_name_key_sensitive_chec CHECK (prsnl_group_name_key is null);
ALTER TABLE cerner.prsnl_group add CONSTRAINT prsnl_group_name_sensitive_chec CHECK (prsnl_group_name is null);
ALTER TABLE cerner.research_account add CONSTRAINT name_key_sensitive_chec CHECK (name_key is null);
ALTER TABLE cerner.research_account add CONSTRAINT name_sensitive_chec CHECK (name is null);


-- ALTER TABLE cerner.address ADD CONSTRAINT parent_entity_name_sensitive_check CHECK (parent_entity_name is null);
-- ALTER TABLE cerner.long_blob ADD CONSTRAINT parent_entity_name_sensitive_check CHECK (parent_entity_name is null);
-- ALTER TABLE cerner.organization ADD CONSTRAINT ft_entity_name_sensitive_check CHECK (ft_entity_name is null);
-- ALTER TABLE cerner.organization ADD CONSTRAINT org_name_key_a_nls_sensitive_check CHECK (org_name_key_a_nls is null);
-- ALTER TABLE cerner.organization ADD CONSTRAINT org_name_key_nls_sensitive_check CHECK (org_name_key_nls is null);
-- ALTER TABLE cerner.organization ADD CONSTRAINT org_name_key_sensitive_check CHECK (org_name_key is null);
-- ALTER TABLE cerner.organization ADD CONSTRAINT org_name_sensitive_check CHECK (org_name is null);
-- ALTER TABLE cerner.prsnl ADD CONSTRAINT ft_entity_name_sensitive_check CHECK (ft_entity_name is null);
-- ALTER TABLE cerner.service_resource ADD CONSTRAINT medical_director_name_sensitive_check CHECK (medical_director_name is null);